apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rhtap14-gitspringart-test 
  janus-idp.io/tekton: rhtap14-gitspringart-test
  backstage.io/kubernetes-id: rhtap14-gitspringart-test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhtap14-gitspringart-test
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  