apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhtap14-gitspringart-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap14-gitspringart-test 
  name: rhtap14-gitspringart-test
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rhtap14-gitspringart-test 
